platform :ios, '11.0'

target 'JobMirron' do
  
  use_frameworks!
  
  source 'https://github.com/CocoaPods/Specs.git'
  source 'https://github.com/CocoaPods/Specs'
  source 'https://cdn.cocoapods.org/'
  
  pod 'Firebase/Storage'
#  pod 'Firebase/Firestore'
  pod 'Firebase/Analytics'
  pod 'FirebaseUI/Facebook'
  pod 'Firebase/Auth'
#  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Database'
  pod 'FirebaseUI/Auth'
  pod 'GoogleSignIn'
  pod 'SwiftMessages'
#  pod 'ReachabilitySwift'
  pod 'DateTools'
  pod 'IQKeyboardManagerSwift'
  pod 'Material', '3.1.8'
#  pod 'SwipeableTabBarController'
end

# Post install script

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete('CODE_SIGNING_ALLOWED')
      config.build_settings.delete('CODE_SIGNING_REQUIRED')
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['ARCHS'] = '$ARCHS_STANDARD_64_BIT'
      config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
    end
  end
end
